var starWarsArr = [
    {
        q:"What is the name of Han Solo’s ship?",
        a:"Millenium Falcon",
        btn1:"Star Destroyer",
        btn2:"Millenium Falcon",
        btn3:"Sliver Bullet"
    },
    {
        q:"What is the weapon used by Jedi Knights?",
        a:"Lightsaber",
        btn1:"Lightsaber",
        btn2:"Blaster",
        btn3:"The Force"
    },
    {
        q:"Which young Jedi Knight becomes Darth Vader in Star Wars: Episode III Revenge of the Sith?",
        a:"Anakin Skywalker",
        btn1:"Luke Skywalker",
        btn2:"Qui Gon Jinn",
        btn3:"Anakin Skywalker"
    },
    {
        q:"What Jedi Master spent 800 years training such pupils as Qui-Gon Jinn Obi-Wan Kenobi, Count Dooku and Luke Skywalker?",
        a:"Yoda",
        btn1:"Yaddle",
        btn2:"Yoda",
        btn3:"Sifo-Dyas"
    },
    {
        q:"What Wookiee is Han Solo’s loyal friend and first mate?",
        a:"Chewie",
        btn1:"Chewie",
        btn2:"C3PO",
        btn3:"Princess Leia"
    },
    {
        q:"Who is Luke and Leia’s mother?",
        a:"Padme Amidala",
        btn1:"Queen Breha Organa",
        btn2:"Shmi Skywalker",
        btn3:"Padme Amidala"
    },
    {
        q:"How many members are there in the Jedi Council?",
        a:"12",
        btn1:"12",
        btn2:"13",
        btn3:"11"
    },
    {
        q:"Why did Yoda say he didn’t want to train Luke Skywalker?",
        a:"Because he lacked patience",
        btn1:"Because he lacked talent",
        btn2:"Because he wanted to be a jedi for the wrong reason",
        btn3:"Because he lacked patience"
    },
    {
        q:"In the Star Wars film, what invisible power binds the galaxy together?",
        a:"The Force",
        btn1:"The Force",
        btn2:"The Magic",
        btn3:"Mitichlorians"
    },
    {
        q:"Who are the masters of the Dark Side who want to rule the galaxy?",
        a:"The Sith",
        btn1:"The Senate",
        btn2:"The Sith",
        btn3:"The Jedi Council"
    },
    {
        q:"What were the last words spoken in The Empire Strikes Back?",
        a:"May the force be with you",
        btn1:"May the force be with you",
        btn2:"Do or do not, there is no try",
        btn3:"Luke, I am your father"
    },
    {
        q:"What animals did the visual effects crew study when designing the Imperial Walkers from The Empire Strikes Back?",
        a:"Elephants",
        btn1:"Hippos",
        btn2:"Elephants",
        btn3:"Giraffes"
    },
    {
        q:"Which country was the home base for principal photography on Revenge of the Sith?",
        a:"Australia",
        btn1:"Egypt",
        btn2:"Tunisia",
        btn3:"Australia"
    },
    {
        q:"Which Star Wars movie was the first to be shot entirely with high-definition cameras, without using traditional 35-millimeter film?",
        a:"Attack of the Clones",
        btn1:"Revenge of the Sith",
        btn2:"Attack of the Clones",
        btn3:"Return of the Jedi"
    },
    {
        q:"What U.S. magazine declared Star Wars “the year’s best movie” in its May 30, 1977, issue?",
        a:"Time",
        btn1:"Time",
        btn2:"Forbes",
        btn3:"Rolling Stones"
    },
    {
        q:"Which star of Revenge of the Sith is the real-life nephew of Denis Lawson, who played Wedge in the first Star Wars Trilogy?",
        a:"Ewan McGreggor",
        btn1:"Harrison Ford",
        btn2:"Ewan McGreggor",
        btn3:"Liam Neeson"
    },
    {
        q:"According to Star Wars legend, what substance powers lightsabers?",
        a:"Ilum Crystals",
        btn1:"Karma Crysta;s",
        btn2:"Force Crystals",
        btn3:"Ilum Crystals"
    },
    {
        q:"How much does the Chewbacca costume weigh?",
        a:"8 lbs",
        btn1:"9 lbs",
        btn2:"8 lbs",
        btn3:"10 lbs"
    },
    {
        q:"Yoda did not make an appearance in only one of the six Star Wars movies. Which one?",
        a:"Star Wars: Episode IV A New Hope",
        btn1:"Star Wars: Episode IV A New Hope",
        btn2:"Star Wars: Episode I The Phantom Menace",
        btn3:"Star Wars: Episode IX The Rise of Skywalker"
    },
    {
        q:"What famous scientist was the inspiration for creature designer Stuart Freeborn when creating Yoda’s eyes?",
        a:"Albert Einstein",
        btn1:"Isaac Newton",
        btn2:"Albert Einstein",
        btn3:"Stephen Kawking"
    },
    {
        q:"Padmé Amidala is first queen of, and then the senator from, what peaceful planet?",
        a:"Naboo",
        btn1:"Tatooine",
        btn2:"Coruscant",
        btn3:"Naboo"
    },
    {
        q:"What Ewok medicine man presided over the attempt to make a roast of Han Solo in Return of the Jedi?",
        a:"Logray",
        btn1:"Logray",
        btn2:"Lemu",
        btn3:"Largay"
    },
    {
        q:"Lando Clarissian’s operation on Cloud City mines what type of gas?",
        a:"Tibanna Gas",
        btn1:"Tintin Gas",
        btn2:"Tarnate Gas",
        btn3:"Tibanna Gas"
    },
    {
        q:"The Empire attacked the Rebel base on Hoth with four-legged Imperial Walkers, or AT-ATs. What does AT-AT stand for?",
        a:"All terrain-Armored Transport",
        btn1:"All terrain-Alternative Tranport",
        btn2:"All terrain-Armored Transport",
        btn3:"All terrain-Attack transport"
    },
    {
        q:"What planet is home to Chewbacca and the Wookiees?",
        a:"Kashyyyk",
        btn1:"Kashyyyk",
        btn2:"Jundland",
        btn3:"Degobah"
    },
    {
        q:"What is the species of the diminutive workers on Cloud City who helped freeze Han Solo in carbonite?",
        a:"Ugnaughts",
        btn1:"Sand People",
        btn2:"Ugnaughts",
        btn3:"Gungan"
    },
    {
        q:"What type of battle armor does Boba Fett wear?",
        a:"Mandalorian",
        btn1:"Mandalorian",
        btn2:"Bounty Hunter",
        btn3:"Jedi"
    },
    {
        q:"Han Solo upgraded his beloved Millennium Falcon from which stock starship?",
        a:"The YT-1300 stock light freighter",
        btn1:"L3",
        btn2:"The YT-1300 stock light freighter",
        btn3:"Death Star"
    },
    {
        q:"What color is Yoda’s lightsaber in Attack of the Clones and Revenge of the Sith?",
        a:"Green",
        btn1:"Yellow",
        btn2:"Blue",
        btn3:"Green"
    },
    {
        q:"Complete this line from A New Hope: “The ____________ Wastes are not to be traveled lightly.",
        a:"Jundland",
        btn1:"Degobah",
        btn2:"Naboo",
        btn3:"Jundland"
    },
    {
        q:"Who preceded Senator Palpatine as Chancellor of the Galactic Senate?",
        a:"Chancellor Valorum",
        btn1:"Chancellor Karpana",
        btn2:"Chancellor Kaj",
        btn3:"Chancellor Valorum"
    },
    {
        q:"Bail Organa is Princess Leia’s adoptive father. What is her adoptive mother’s name?",
        a:"Queen Breha Organa",
        btn1:"Queen Padme Amidala",
        btn2:"Queen Breha Organa",
        btn3:"Queen Jamillia"
    },

]

